// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADf9ZH8RZ8crrpxqDNEzA_i9eeZmvvYyY',
    appId: '1:416324544389:web:c9a452236d03ed222206ec',
    messagingSenderId: '416324544389',
    projectId: 'super-mario-921e8',
    authDomain: 'super-mario-921e8.firebaseapp.com',
    storageBucket: 'super-mario-921e8.firebasestorage.app',
    measurementId: 'G-ZV6FE520D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBnxMUI0UE4wUvboJKAP7PXj4QmDFowk',
    appId: '1:416324544389:android:3951c18003c3db0c2206ec',
    messagingSenderId: '416324544389',
    projectId: 'super-mario-921e8',
    storageBucket: 'super-mario-921e8.firebasestorage.app',
  );

}